### ISSUE TITLE
Support for continuous learning or resume training

### ISSUE THREAD

**Issue by GokulNC** [myudelson/hmm-scalable#3]
Hi @myudelson ,

Is it possible to support continuous learning in this repo?
That is, like real-time fine-tuning of the model as we receive more student data (in batches).

One quick and simple suggestion would be, loading the model that's passed via command-line to the `trainhmm` binary.
That is, if the model file exists, we can load the already learnt parameters from the file into the respective buffers, and start (resume) training.

Is that possible?

Thanks a lot!
Gokul NC

**Comment by GokulNC** [comment]
It seems like there is already a member function called `readModelBody()` for each `HMMProblem` class.
Will it be possible to use that to achieve the above?

**Comment by myudelson** [comment]
Gokul,

Exactly. You could specify an existing model file in -0 setting, instead of
seed parameters universal to all skills.
Then you could either use an extended data (old and new) or only the new
data.

I need to create a new guide for the utility to cover these topics, it
seems :).

Best,
Michael

--
Michael V. Yudelson
Sr. Software Engineer
ACT, Inc.

**Comment by GokulNC** [comment]
Thanks Michael, that helped.
Yes, it would be better if you could mention about the argument `-0 <params_file>` in the README.
Please feel free to close this issue after it is handled. :)
