### ISSUE TITLE
[Feature Request] Support for AUC Metric

### ISSUE THREAD

**Issue by GokulNC** [myudelson/hmm-scalable#4]
Hi @myudelson ,

Will it be possible to add support for AUC metric also for evaluation?
Most KT papers seem to be reporting using that metric as a standard.

BTW, I see that there is support for [AIC metric](https://github.com/myudelson/hmm-scalable/blob/d1da8ec/trainhmm.cpp#L390).
But I am not sure how to add support for AUC metric.

It would be great if you can take this as a feature request, or guide me on how to go about adding it.

Thanks a lot!

**Comment by myudelson** [comment]
Gokul,
Indeed, AUC is a nifty measure. I myself was computing it for some of the
papers.
One could compute it post hoc from correctness column and predicted
correctness column. For example, using pROC package from R.
It is a great feature to add, I'll take this request. Cannot promise to
fulfill it soon though.
Best,
Michael

**Comment by rajm23sc** [comment]
@GokulNC when I am training I am not able to get good accuracy, is this because of my student-skill attemp sequence length distribution 

mean            1.97187
std             2.38603
min             1.00000
1%              1.00000
5%              1.00000
15%             1.00000
25%             1.00000
50%             1.00000
75%             2.00000
95%             6.00000
99%            11.00000
max           744.00000

above is the distribution of attempt sequence length (last column below)
student_1 skillA 1,2,1,2,1,1,1  7
student_1 skillA 1,2,1,1          4
student_2 skillB 1,2.             2


Also in the public dataset algebra _2008_2009.txt (accuracy of 90%) the same distribution looks like below: 
count    33828.000000
mean       263.629360
std        217.955443
min          1.000000
1%           7.000000
5%          30.000000
15%         82.000000
25%        119.000000
50%        206.000000
75%        343.000000
99%       1034.000000
max       2226.000000

**Comment by myudelson** [comment]
Gokul,
It looks like your data is predominantly single student engagement with a skill. Given that, BKT might not be the best model. Some form of IRT or MIRT would do better.
Best,
Michael
